.PHONY : ALL
ALL :  linklist reverse_linklist

linklist:
	g++ -g -Wall -o linklist linklist.cc
reverse_linklist:
	g++ -g -Wall -o reverse_linklist reverse_linklist.cc

.PHONY : clean
clean : 
	 rm -rf core  linklist reverse_linklist
