.PHONY : ALL
ALL :  double_linkedlist linklist reverse_linklist

double_linkedlist:
	g++ -g -Wall -o double_linkedlist double_linkedlist.cc
linklist:
	g++ -g -Wall -o linklist linklist.cc
reverse_linklist:
	g++ -g -Wall -o reverse_linklist reverse_linklist.cc

.PHONY : clean
clean : 
	 rm -rf core  double_linkedlist linklist reverse_linklist
